#!/bin/bash
# Run one job of the 10-seed sweep: every training run listed in a manifest,
# sequentially.  Generated by make_seed_sweep.py; queued by condor/sweep.sub.
#
#   condor/run_manifest.sh condor/sweep_manifests/job_07.txt
#
# Manifest lines are TSV:  <expected_dir> <produced_dir> <20 execute_don.py args>
# where produced_dir differs from expected_dir only for the fig. 4 nets, which
# execute_don.py writes as '_expA<e>' when adaptiveLR=1 and which the analysis
# scripts expect as '_exp<e>'.
#
# COMPLETENESS GUARD.  execute_don.py skips any net whose directory already
# exists, without checking that it finished -- so a run killed by preemption
# leaves a partial directory that every later attempt silently skips.  Here we
# instead require the LAST checkpoint (<Nep-99>cur_chp; checkpoints are written
# at i%100==0 as <i+1>) and delete anything incomplete before retraining.  That
# makes the whole sweep idempotent: resubmit the same jobs and only unfinished
# work runs again.
set -uo pipefail

MANIFEST="${1:?usage: run_manifest.sh <manifest file>}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
NETS="${REPO_ROOT}/data/nets"

# The training loop runs with cwd=src/, so the manifest path must be absolute
# before we get there -- a relative one would silently resolve to src/... and
# the loop would read nothing.
[[ "${MANIFEST}" != /* ]] && MANIFEST="${REPO_ROOT}/${MANIFEST}"
if [[ ! -s "${MANIFEST}" ]]; then
    echo "ERROR: manifest ${MANIFEST} is missing or empty" >&2
    exit 3
fi
N_LINES=$(grep -c . "${MANIFEST}")

if [[ -f "${REPO_ROOT}/.venv-linux/bin/activate" ]]; then
    # shellcheck disable=SC1091
    source "${REPO_ROOT}/.venv-linux/bin/activate"
else
    echo "ERROR: no .venv-linux — run condor/build_env.sub first." >&2
    exit 1
fi

export JAX_PLATFORMS=cpu
export MPLBACKEND=Agg
export CUDA_VISIBLE_DEVICES=""
export TMPDIR="${_CONDOR_SCRATCH_DIR:-${TMPDIR:-/tmp}}"

NCPUS="${OMP_NUM_THREADS:-4}"
export OMP_NUM_THREADS="${NCPUS}"
export OPENBLAS_NUM_THREADS="${NCPUS}"
export MKL_NUM_THREADS="${NCPUS}"
export NUMEXPR_NUM_THREADS="${NCPUS}"
export XLA_FLAGS="--xla_cpu_multi_thread_eigen=true intra_op_parallelism_threads=${NCPUS}"

echo "host=$(hostname) cpus=${NCPUS} manifest=${MANIFEST}"
cd "${REPO_ROOT}/src"

n_done=0; n_skip=0; n_fail=0; n_repair=0
JOB_START=$(date +%s)

while IFS=$'\t' read -r EXPECTED PRODUCED ARGS; do
    [[ -z "${EXPECTED:-}" ]] && continue

    NEP="${ARGS%% *}"                     # first argument is Nepochs
    FINAL_CHP="$(( NEP - 99 ))cur_chp"    # last checkpoint execute_don.py writes

    if [[ -f "${NETS}/${EXPECTED}/${FINAL_CHP}" ]]; then
        echo "SKIP   complete: ${EXPECTED}"
        n_skip=$((n_skip + 1))
        continue
    fi

    # Incomplete or absent: clear both possible names so execute_don.py re-runs.
    for d in "${EXPECTED}" "${PRODUCED}"; do
        if [[ -d "${NETS}/${d}" ]]; then
            echo "REPAIR removing incomplete ${d}"
            rm -rf "${NETS:?}/${d}"
            n_repair=$((n_repair + 1))
        fi
    done

    echo "TRAIN  ${EXPECTED}"
    START=$(date +%s)
    # shellcheck disable=SC2086
    if ! python execute_don.py ${ARGS}; then
        echo "FAIL   ${EXPECTED}"
        n_fail=$((n_fail + 1))
        continue
    fi
    ELAPSED=$(( $(date +%s) - START ))

    # fig. 4 only: rename '_expA<e>' -> '_exp<e>' so the analysis scripts find it.
    if [[ "${PRODUCED}" != "${EXPECTED}" && -d "${NETS}/${PRODUCED}" ]]; then
        echo "RENAME ${PRODUCED} -> ${EXPECTED}"
        mv "${NETS}/${PRODUCED}" "${NETS}/${EXPECTED}"
    fi

    if [[ -f "${NETS}/${EXPECTED}/${FINAL_CHP}" ]]; then
        echo "DONE   ${ELAPSED}s ${EXPECTED}"
        n_done=$((n_done + 1))
    else
        echo "FAIL   finished but ${FINAL_CHP} missing: ${EXPECTED}"
        n_fail=$((n_fail + 1))
    fi
done < "${MANIFEST}"

echo "SUMMARY manifest=${MANIFEST} trained=${n_done} skipped=${n_skip} repaired=${n_repair} failed=${n_fail} of ${N_LINES} job_seconds=$(( $(date +%s) - JOB_START ))"

# Doing nothing is a failure, not a success: it means the manifest was unreadable
# or every line was malformed. Without this the job exits 0 having trained nothing.
if [[ $(( n_done + n_skip )) -ne ${N_LINES} ]]; then
    echo "ERROR: accounted for $(( n_done + n_skip )) of ${N_LINES} manifest lines" >&2
    exit 4
fi
[[ ${n_fail} -eq 0 ]]
